### ISSUE TITLE
Missing "change" event

### ISSUE THREAD

**Issue by darkoromanov** [dbrekalo/vue-date-pick#1]
Hi there,

this plugin is currently one of the best I found for Vue, good job! The only thing I miss is a "change" event, this is something  I really need because I have 2 datepickers and they have to change value whenever the user change date on one of them.

**Comment by dbrekalo** [comment]
Glad you like plugin. Vue v-model="date" directive is just a shorter way to write v-bind:value="date" v-on:input="date = $event". Input event might be this change event you seek. Can you work with that?

**Comment by darkoromanov** [comment]
I preferred to use watch, thanks.

**Comment by pankajsanam** [comment]
+1 for this. I am having issues and really need a change event because it's a dynamic form.

**Comment by dbrekalo** [comment]
Date picker fires standard “input” event (as this is common practice with all v-model components). Use input event to watch for changes. Hope this helps

**Comment by WebMedic-X** [comment]
Hi

It's not clear how to listen to input event changes, do you mind sharing an example?

Thanks
