### ISSUE TITLE
Set class for input

### ISSUE THREAD

**Issue by manhtqb** [dbrekalo/vue-date-pick#10]
Hello, I wonder if I can set class for input tag? I tried using` :class` or `:input-class` but only set it to the div outside the input tag. Thanks for reading !

**Comment by dbrekalo** [comment]
inputAttributes prop can be used to set input class (and other attributes like name, placeholder, id...).

This is hinted in docs (https://dbrekalo.github.io/vue-date-pick/examples.html#disabling-manual-input).
