### ISSUE TITLE
Allow precise year / month selection

### ISSUE THREAD

**Issue by keith0305** [dbrekalo/vue-date-pick#11]
I know we can customize the year range using selectableYearRange, but I wanted more control over which year I choose to show.

For e.g. I do not want year 2018 and before, but want to show 2019 and 2020.

Would be great if this feature is added in the next update. I will try to tinker with the source code myself in the meantime.

**Comment by r-moore** [comment]
Yes it would be great if selectableYearRange could allow only past dates, or future dates.

The current default +/- 40 years doesn't suit many use cases (e.g. if I want a date of birth selector).

I know I can filter using isDateDisabled but this doesn't actually *hide* those disabled dates from the month/year selectors in the header.

**Comment by MOM20190410** [comment]
wish this component can provide "month", "quarter", "week" UI seperately. thank you:)

**Comment by ReneKofler** [comment]
I would also love it, that if you disable Dates, that the popup not starts on disabled dates. e.g. i have such a usecase, where I don't want to allow birthdates before 18 years, but the Popup starts on the current date ...

**Comment by dbrekalo** [comment]
Api updated in version 1.3.0 -> https://dbrekalo.github.io/vue-date-pick/examples.html#change-selectable-years

**Comment by keith0305** [comment]
Just wanted to say thank you! <3
