### ISSUE TITLE
Allow 12h clock (AM/PM)

### ISSUE THREAD

**Issue by WayneUong** [dbrekalo/vue-date-pick#12]
Is this functionality supported? Thank you. It's a great package otherwise.

**Comment by dhavald99** [comment]
is there any update on this ??  i also want same  

Thanks @dbrekalo

**Comment by dbrekalo** [comment]
Added in version 1.4.0. [Example is here.](https://dbrekalo.github.io/vue-date-pick/examples.html#date-time-picker-am-pm)
