### ISSUE TITLE
props: "inputAttributes" not working

### ISSUE THREAD

**Issue by liskovoy** [dbrekalo/vue-date-pick#15]
https://dbrekalo.github.io/vue-date-pick/examples.html#disabling-dates

not working:

```
<date-pick
  v-model="date"
  :inputAttributes="{readonly: true}">
</date-pick>
```

works:

```
<date-pick
  v-model="date"
  :input-attributes="{readonly: true}">
</date-pick>
```

**Comment by liskovoy** [comment]
I'm sorry, it's my mistake.

**Comment by lggwettmann** [comment]
Could you update this in the docs perhaps? I also just copied the code and wondered why it's not working ;) Thanks.
