### ISSUE TITLE
Array of dates disabled

### ISSUE THREAD

**Issue by luisfpc91** [dbrekalo/vue-date-pick#16]
Is posibled send a array of dates disabled?

**Comment by laemol** [comment]
I have implemented it by adding a new prop like so:

`export default {
    components: {DatePick},
    props: ['scheduleData'],`

And passing it to the component like this:

`<calendar-component :schedule-data="'{{ json_encode($schedule) }}'"`

Wehere the $schedule variable is my php dates array.

And then using the method as documented [here](https://dbrekalo.github.io/vue-date-pick/examples.html#disabling-dates)

`methods: {
        isDisabledDate(date) {
            let dates = this.scheduleData
            let d = date
            date = [d.getFullYear(), ('0' + (d.getMonth() + 1)).slice(-2),('0' + d.getDate()).slice(-2)].join('-');   
            return dates.includes(date)
        }
    }`

**Comment by dbrekalo** [comment]
It is easily achievable via isDateDisabled check:
```js
isDateDisabled(dateObject) {
   return ['2019-08-20', '2019-08-30'].includes(
      formatDate('YYYY-MM-DD')
   );
} 
```

**Comment by iosiflivadaru** [comment]
@dbrekalo I get error formatDate is not a function... and also what is the point of "dateObject" as a parameter to the method?
