### ISSUE TITLE
hasInputElement does not render as calendar widget

### ISSUE THREAD

**Issue by lggwettmann** [dbrekalo/vue-date-pick#20]
Hey,

thanks for the nice vue component. I can't seem to get vue-date-pick to work as a calendar widget by setting :hasInputElement="false". Any tips?

**Comment by justinhartman** [comment]
+1 Same issue.

**Comment by lggwettmann** [comment]
Sorry, didn't end up using it because of this bug and deleted it out of the code-base. Perhaps @justinhartman has some tips on this?
