### ISSUE TITLE
Not working properly inside a b-tab (bootstrap-vue)

### ISSUE THREAD

**Issue by diguifi** [dbrekalo/vue-date-pick#23]
I didn't really know if I should issue this here or on [bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue)'s repository, but I decided to post here because default calendars work well inside the `b-tab` component of bootstrap-vue.

When trying to use this component inside a [b-tab](https://bootstrap-vue.js.org/docs/components/tabs/), like so:
```js
        <b-tabs>
            <b-tab title="first">
                <date-pick v-model="date"></date-pick>
            </b-tab>
            <b-tab title="second"></b-tab>
        </b-tabs>
```
it gets rendered and I can type a date inside it, but when selecting a day from the calendar with a click, it won't work and I can't understand why. Anywhere else its working perfectly, the problem only occurs inside `b-tab`

**Comment by diguifi** [comment]
Closing this issue because I tried to make a pen and test it, and it worked, so it's not an issue with this package, it's probably something wrong with our on code.

[Demo pen](https://codepen.io/diguifi/pen/zXZyPz)

**Comment by alexraileanu** [comment]
@diguifi did you figure out what the issue was? i'm having a similar problem but inside a modal rather than a tab.
