### ISSUE TITLE
selectableYearRange atrribute design is not so well

### ISSUE THREAD

**Issue by RunningV** [dbrekalo/vue-date-pick#25]
why it's been designed selectableYearRange a number, you can just  use startDate && endDate to set years range let us define it. Your code is use current time as a center time line. how can i  use a year  until this year ?

**Comment by caughtrandomly** [comment]
You can't, I've found the same issue, I'm pulled requested for the ability to set to disable past years or future years, but maybe pull request this in? Sounds like a good feature.

**Comment by dbrekalo** [comment]
If we allow selectableYearRange prop to be array (for example [1995, 2001]) or function that returns array ([2018, 2020]) - will this cover your use cases?

**Comment by RunningV** [comment]
It's good, i wish u can complete it . this datepicker's UI is very beautiful. 
Even more, i wish another function : it can be click a button trigger to toggle calendar. but this is not so instantly, i can hack it .

**Comment by MOM20190410** [comment]
wish this component can provide "month", "quarter" UI seperately.

**Comment by Tusko** [comment]
any updates?

**Comment by dbrekalo** [comment]
Api updated in version 1.3.0 -> https://dbrekalo.github.io/vue-date-pick/examples.html#change-selectable-years
