### ISSUE TITLE
Disabling dates with an array

### ISSUE THREAD

**Issue by Dalt0x** [dbrekalo/vue-date-pick#31]
I'm trying to send an array of dates to choose which dates i don't want to disabling. Thre's any way to do that with an array or similar?

Example: 
:isDateDisabled=[2019-08-20, 2019-08-30, ...]

**Comment by dbrekalo** [comment]
It is easily achievable via isDateDisabled check:
```js
isDateDisabled(dateObject) {
   return ['2019-08-20', '2019-08-30'].includes(
      formatDate('YYYY-MM-DD')
   );
} 
```
