### ISSUE TITLE
Feature: Programmatic way to set the current month showing without changing value

### ISSUE THREAD

**Issue by CalebPourchot** [dbrekalo/vue-date-pick#32]
Great component. Thanks.

I'm wondering if you could add a way to set the current date showing in the calendar without actually setting the value. I have a two-calendar view to set independent start and end dates and I want to sync the view of the end calendar with the start calendar. 

Maybe it could be another prop for the viewable date or something like that.

**Comment by dbrekalo** [comment]
It is available from version 1.4.0. [Look for example here](https://dbrekalo.github.io/vue-date-pick/examples.html#custom-start-period).

**Comment by CalebPourchot** [comment]
Thanks for this. Looks like the prop isn't watched though? So, when I pick a later date in my "start" calendar, updating the startPeriod doesn't refresh the "end" calendar.
