### ISSUE TITLE
Small update for weekdays rendering

### ISSUE THREAD

**Issue by maestroDever** [dbrekalo/vue-date-pick#34]
I just wanted to customize the date picker look like below.
![image](https://user-images.githubusercontent.com/48345279/66864752-85ca2700-ef9e-11e9-882d-b60e47fca1bd.png)
Note that I want to use only the first letters of weekday names.
So I put like this.
```
<date-pick
    v-model="date"
    :startWeekOnSunday="true"
    :weekdays="['M', 'T', 'W', 'T', 'F', 'S', 'S']"
  />
```
But then I got this error.
![image](https://user-images.githubusercontent.com/48345279/66864836-b7db8900-ef9e-11e9-83ee-92e5b4d68621.png)
No wonder. Looking at the source code, I found this:
![image](https://user-images.githubusercontent.com/48345279/66864893-d93c7500-ef9e-11e9-8d9c-4788cb9ccdd4.png)
Just a small update will fix this issue.
```
<th class="vdpHeadCell" v-for="(weekday, index) in weekdaysSorted" v-bind:key="index">
    <span class="vdpHeadCellContent">{{weekday}}</span>
</th>
```
Hope contributors can take a look and consider updating this. Otherwise, let me know please if there could be any other turnaround.
Thanks

**Comment by dbrekalo** [comment]
Fixed in version 1.3.0
