### ISSUE TITLE
[Feature Request] introduce custom slot behaviour to attach date-pick to any custom element

### ISSUE THREAD

**Issue by vesper8** [dbrekalo/vue-date-pick#36]
I'm considering switching over from v-calendar and one thing that I'm missing which is very easy to accomplish with v-calendar (v-date-picker in specific) is the ability to add a custom element inside the default slot and have any element, an input, a button, an image, replace the default input.

This feature is detailed here https://vcalendar.io/datepicker.html#custom-slot

This would allow someone to this for example:

```
<date-pick
        v-model="date"
        :format="'YYYY.MM.DD'"
    >
  <button class="p-2 bg-blue-500 hover:bg-blue-600 text-white rounded focus:outline-none">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 20 20"
      class="w-4 h-4 fill-current">
      <path d="M1 4c0-1.1.9-2 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4zm2 2v12h14V6H3zm2-6h2v2H5V0zm8 0h2v2h-2V0zM5 9h2v2H5V9zm0 4h2v2H5v-2zm4-4h2v2H9V9zm0 4h2v2H9v-2zm4-4h2v2h-2V9zm0 4h2v2h-2v-2z" />
    </svg>
  </button>
</date-pick>
```

Would be very welcome if you could add this.. that is if it's not already possible.. I admit I didn't try it but didn't see anything about slots mentioned in the documentation

Thank you!

**Comment by dbrekalo** [comment]
Great suggestion - it is now available in version 1.4.0+ and [documented with example here](https://dbrekalo.github.io/vue-date-pick/examples.html#custom-content-with-slot)
