### ISSUE TITLE
How I can put Date object as input value (v-model)?

### ISSUE THREAD

**Issue by Iguana59** [dbrekalo/vue-date-pick#38]
Hi. I can't put as input value Date object -> 
` <date-pick name="start" class="datePick" v-model="selectedEvent.startDate" :pickTime="true"
                          :parseDate="parseDate"  :isDateDisabled="isPreviousDate"></date-pick>`

where selectedEvent.startDate - is Date object, 
           displayFormat: 'DD/MM/YYYY HH:mm',
          parseDate (dateString, format) {
              return moment(dateString).format(this.displayFormat)
            },
and I receive error [Vue warn]: Invalid prop: type check failed for prop "value". Expected String with value "Fri Jan 24 2020 00:00:00 GMT+0200 (Eastern European Standard Time)", got Date

Please help)

**Comment by dbrekalo** [comment]
Value cannot be Date Object, string type for value is expected

**Comment by Iguana59** [comment]
@dbrekalo I think this is very uncomfortable, because many libs operates with Date Objects, that is why using vue-date-pick we should firstly convert from object to String and when choose special date - convert it from string to object.
