### ISSUE TITLE
The component doesn't render

### ISSUE THREAD

**Issue by Eworm** [dbrekalo/vue-date-pick#4]
I followed the instructions, but I can't get the datepicker to render anything in the DOM. I use VUE 1.0.28. The Datepick component is visible in the Chrome Vue inspector, but the DOM is empty. Any thoughts on why this is happening?

Below a screenshot of the inspector:

<img width="329" alt="schermafbeelding 2018-12-11 om 16 20 12" src="https://user-images.githubusercontent.com/511488/49810063-ac0cae00-fd60-11e8-8c17-ad2186e5aded.png">

**Comment by dbrekalo** [comment]
Only Vue in version 2+ is supported.
