### ISSUE TITLE
The selected date cannot be localized

### ISSUE THREAD

**Issue by AriDeer** [dbrekalo/vue-date-pick#42]
Initially, the names of the months are localized, but when we select a date the data returned is in English.

![image](https://user-images.githubusercontent.com/4179565/75430010-efe8d480-595f-11ea-9cf8-14c08ba9c188.png)

![image](https://user-images.githubusercontent.com/4179565/75430176-33434300-5960-11ea-991e-892c05d6f023.png)

**Comment by dbrekalo** [comment]
Check your implementation of parseDate/formatDate props against demo examples. 

Hope this helps!
