### ISSUE TITLE
remove focusin after removeCloseEvent

### ISSUE THREAD

**Issue by zWingz** [dbrekalo/vue-date-pick#44]
![image](https://user-images.githubusercontent.com/13031838/76820643-bf9da300-6846-11ea-8ecd-d9556c1bcb5f.png)
![image](https://user-images.githubusercontent.com/13031838/76820654-c4faed80-6846-11ea-9424-f3eaea6067d9.png)

**Comment by loeffel-io** [comment]
We need this too! Is the project dead?

**Comment by dbrekalo** [comment]
Good catch, fixed in version ^1.3.0.
