### ISSUE TITLE
Textbox not needed

### ISSUE THREAD

**Issue by Gruski** [dbrekalo/vue-date-pick#47]
How do I get rid of the text box. I just need the calendar to be bound to a vue data field but not have the component render an <input type=text>. Also need to open the calendar from my own button element not tied to the built in <input type=text>. Is this possible?

**Comment by dbrekalo** [comment]
It is possible in versions 1.4.0+. [Example can be seen here.](https://dbrekalo.github.io/vue-date-pick/examples.html#custom-content-with-slot)
