### ISSUE TITLE
datepicker doesn't close

### ISSUE THREAD

**Issue by IrynaSamoila** [dbrekalo/vue-date-pick#6]
Hi!
Datepicker doesn't close after losing focus by keyboard (TAB). 

Steps to reproduce: 
 * Open datepicker 
 * Press Tab button until another element on page get focus

Expected behaviour:
 * Datepicker picked closed, next page element focused

Current  behaviour:
 * Next page element focused
 * Datepicker stays open

This is critical for me, can you fix this? 

![image](https://user-images.githubusercontent.com/8299232/51179878-10bea980-18c7-11e9-91ab-e7d7f64fb259.png)

**Comment by dbrekalo** [comment]
@IrynaSamoila fixed in version 1.0.6
