### ISSUE TITLE
Typing a date manually not working correctly

### ISSUE THREAD

**Issue by Triasto** [dbrekalo/vue-date-pick#9]
Thanks for creating this plugin, I think it's way more straight forward then the other vue-date-picker that's available.

But I'm encountering a small issue:

When typing a date manually it autocompletes while typing, 
The function processUserInput parses to soon or at least incorrect

When using the format: DD-MM-YYYY 
Autocompletion gets triggered after typing:

20-02-1

While typing the above sentence it autcompletes to : 20-02-1901

If you continue typing it just continues after the 1901.

for example typing 20-02-1999 results in : 20-02-1901999

**Comment by conceptual-phuc** [comment]
Same issue

**Comment by dbrekalo** [comment]
Confirmed, will look into it.

**Comment by dbrekalo** [comment]
Fixed in version ^1.1.0
