### ISSUE TITLE
Date picker doesn't work in Chrome Version 127.0.6533.99

### ISSUE THREAD

**Issue by molten-firescar96** [dbrekalo/vue-date-pick#96]
The latest version of chrome changed the order that elements are triggered on a click event. As far as I can tell click events used to propagate down from the user perspective, from the most visible element, to any elements hidden underneath. Now it seems the events start at the "bottom" layer and move up. I'll be switching to a different date picker library for my project, but as a short term patch here's what I did to fix this.

The bug we (and our users) had, was any click on the date picker closed the popup, without selecting a date.

Before
```javascript
        inspectCloseEvent(event) {
            if (event.keyCode) {
                event.keyCode === 27 && this.close();
            } else if (!(event.target === this.$el) && !this.$el.contains(event.target)) {
                this.close();
            }
        },
```

After
```javascript
        inspectCloseEvent(event) {
            if (event.keyCode) {
                event.keyCode === 27 && this.close();
            } else if (!(event.target === this.$el) && !this.$el.contains(event.target) && !event.target.contains(this.$el)) {
                this.close();
            }
        },
```

**Comment by dbrekalo** [comment]
@molten-firescar96 Thanks for reporting, is the issue still present in current chrome version - 127.0.6533.100? I cannot reproduce it there on windows or mac.

**Comment by molten-firescar96** [comment]
Yes a coworker confirmed the bug in version 127.06533.100. We've since started to use a patched version of vue-date-pick, so I won't be able to contribute further. Our longer term move as we finish migrating to vue 3 will be to use antd's date picker.

**Comment by molten-firescar96** [comment]
I tried making a minimal reproducible build, but I couldn't reproduce the issue so I'll close this ticket.
